# -*- coding: utf-8 -*-
"""lab 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZcoDu1_P4axznj5oa1fCsEqpmPJPdpT0
"""

import numpy as np
arr=np.arange(1,11)
print(arr)
print(type(arr))
print(arr.shape)

import numpy as np
zeros=np.zeros((3,3))
ones=np.ones((3,3))
print(zeros)
print(ones)

import numpy as np
arr=np.linspace(0,1,10)
print(arr)

import numpy as np
arr=np.eye(5)
print(arr)

import numpy as np
arr=np.random.randint(1,101,10)
sorted=np.sort(arr)
print(arr)
print("sorted:" ,sorted)

import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))

import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("First 3 elements:", arr[:3])
print("Last 3 elements:", arr[-3:])
print("Middle elements:", arr[3:-3])